################################################################################
# Colors and Styles
################################################################################
colors:
  annual_activities:
    critical_period: "#896279"     
    data: "#000000"                
    forecast: "#3498DB"            
    communication: "#27AE60"        

  snow_forecasting:
    critical_period: "#114b5f"       
    data: "#000000"                  
    forecast: "#377eb8"              
    communication: "#4daf4a"         

  # Hydrological Forecasting Color Scheme
  hydrological_forecasting:
    critical_period: "#187DA9"       
    data: "#000000"                 
    forecast: "#377eb8"              
    communication: "#4daf4a"         

  # River Ice Monitoring Color Scheme
  river_ice_monitoring:
    critical_period: "#3DA5D9"       
    data: "#000000"                
    forecast: "#377eb8"              
    communication: "#4daf4a"         

  # Planning and Improvement Color Scheme
  planning_and_improvement:
    critical_period:  "#B8CEB6"        
    admin: "#666666"                 
    capacity: "#666666"              
    block: "#000000"                


  # Visualization and Other Elements
  visualization:
    snow_survey: "#e41a1c"             # Red
    snow_bulletin: "#4daf4a"           # Green
    spring_breakup_outlook: "#4daf4a"
    streamflow: "#98C8E6"             # Red
    swe: "#B6B8D6"                   # Blue


styles:
  solid:
    linestyle: "-"
    linewidth: 3

  dashed:
    linestyle: "--"
    linewidth: 3

  dotted:
    linestyle: ":"
    linewidth: 3

  dashdot:
    linestyle: "-."
    linewidth: 3

  downward_triangle:
    marker: "v"
    markersize: 10
    markeredgewidth: 2
    markerfacecolor: "visualization.snow_survey"

  diamond:
    marker: "P"
    markersize: 10
    markeredgewidth: 2
    markerfacecolor: "visualization.spring_breakup_outlook"

################################################################################
# Month Ranges
################################################################################
month_ranges:
  Jan: [1, 31]
  Feb: [32, 59]
  Mar: [60, 90]
  Apr: [91, 120]
  May: [121, 151]
  Jun: [152, 181]
  Jul: [182, 212]
  Aug: [213, 243]
  Sep: [244, 273]
  Oct: [274, 304]
  Nov: [305, 334]
  Dec: [335, 365]

################################################################################
# Sectors
################################################################################
sectors:
  Jan: 31
  Feb: 28
  Mar: 31
  Apr: 30
  May: 31
  Jun: 30
  Jul: 31
  Aug: 31
  Sep: 30
  Oct: 31
  Nov: 30
  Dec: 31

################################################################################
# Track Configurations
################################################################################
track_configs:  
  

  #################################################################################
  # Annual Activities
  #################################################################################
  annual_activities:
    type: "infill"
    color: "annual_activities.critical_period"
    alpha: 0.5
    linewidth: 3
    r_start: 101
    r_end: 105
    months: ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]

  CHPS_operations:
    type: "line"
    color: "annual_activities.data"
    linestyle: "dashed"
    linewidth: 3
    r_start: 104
    r_end: 104
    months: ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]

  alaska_stream_gauge_observing_program:
    type: "line"
    color: "annual_activities.data"
    linestyle: "dotted"
    linewidth: 3
    r_start: 102
    r_end: 102
    months: ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]
  #################################################################################
  # Snow Seasonal Forecasting
  #################################################################################
  snow_based_seasonal_forecasts_critical:
    type: "infill"
    color: "snow_forecasting.critical_period"
    alpha: 0.5
    r_start: 87
    r_end: 100
    months: ["Apr", "May","Jun"]
  
  snow_based_seasonal_forecasts_total:
    type: "infill"
    color: "snow_forecasting.critical_period"
    alpha: 0.2
    r_start: 87
    r_end: 100
    months: ["Mar","Apr", "May", "Jun", "Jul"]

  automated_station_data:
    type: "line"
    color: "snow_forecasting.data"
    linestyle: "dashed"
    linewidth: 3
    r_start: 99
    r_end: 99 
    months: ["Mar", "Apr", "May", "Jun", "Jul"]

  large_domain_snow_products_for_snow_forecasting:
    type: "line"
    color: "snow_forecasting.data"
    linestyle: "dotted"
    linewidth: 3
    r_start: 97
    r_end: 97
    months: ["Mar", "Apr", "May"]
  
  temperature_outlook:
    type: "line"
    color: "snow_forecasting.data"
    linestyle: "dashdot"
    linewidth: 3
    r_start: 95
    r_end: 95
    months: ["Mar", "Apr", "May", "Jun", "Jul"]

  snow_based_forecast_1:
    type: "line"
    color: "snow_forecasting.forecast"
    linestyle: "-"
    linewidth: 3
    r_start: 93
    r_end: 93
    months: ["Apr", "May", "Jun", "Jul"]

  snow_based_forecast_2:
    type: "line"
    color: "snow_forecasting.forecast"
    linestyle: "-"
    linewidth: 3
    r_start: 91
    r_end: 91
    months: ["May", "Jun", "Jul"]

  spring_breakup_outlook_snow:
    type: "marker"
    color: "visualization.spring_breakup_outlook"
    marker: "P"
    markersize: 10
    linewidth: 3
    months: ["Apr"]
    r_points:
      Apr: 90
    position: 0

  snow_surveys:
    type: "marker"
    color: "visualization.snow_survey"
    marker: "v"
    markersize: 10
    linewidth: 3
    months: ["Apr", "May"]
    r_points:
      Apr: 93
      May: 91
    position: 0

  #################################################################################
  # Hydrological Short Term
  #################################################################################
  hydrological_critical_period:
    type: "infill"
    color: "hydrological_forecasting.critical_period"
    alpha: 0.7
    r_start: 65
    r_end: 86
    months: ["Apr", "May", "Jun", "Jul","Aug","Sep"]
  
  hydrological_total:
    type: "infill"
    color: "hydrological_forecasting.critical_period"
    alpha: 0.2
    r_start: 65
    r_end: 86
    months: ["Oct", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep"]

  hydrometric_observations:
    type: "line"
    color: "hydrological_forecasting.data"
    linestyle: "-"
    linewidth: 3
    r_start: 84
    r_end: 84
    months: ["Oct", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep"]
  
  large_domain_snow_products_for_hydrological_forecasting:
    type: "line"
    color: "snow_forecasting.data"
    linestyle: "dotted"
    linewidth: 3
    r_start: 82
    r_end: 82
    months: ["Oct", "Mar", "Apr", "May","Sep"]
    
  nwp_forecasts:
    type: "line"
    color: "hydrological_forecasting.data"
    linestyle: "dashed"
    linewidth: 3
    r_start: 80
    r_end: 80
    months: ["Oct", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep"]

  meterologist_input:
    type: "line"
    color: "hydrological_forecasting.data"
    linestyle: "dotted"
    linewidth: 3
    r_start: 78
    r_end: 78
    months: ["Oct", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep"]

  hydrologic_short_term_chps:
    type: "line"
    color: "hydrological_forecasting.forecast"
    linestyle: "dashed"
    linewidth: 3
    r_start: 76
    r_end: 76
    months: [ "Oct",  "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep"]
  
  hydrologic_short_term_hefs:
    type: "line"
    color: "hydrological_forecasting.forecast"
    linestyle: "dotted"
    linewidth: 3
    r_start: 74
    r_end: 74
    months: [ "Oct",  "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep"]

  hydrologic_medium_term_outlook:
    type: "line"
    color: "hydrological_forecasting.forecast"
    linestyle: "dashdot"
    linewidth: 3
    r_start: 72
    r_end: 72
    months: [ "Oct", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep"]

  portal_communication:
    type: "line"
    color: "hydrological_forecasting.communication"
    linestyle: "dotted"
    linewidth: 3
    r_start: 70
    r_end: 70 
    months: [ "Oct", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep"]

  event_based_communication:
    type: "line"
    color: "hydrological_forecasting.communication"
    linestyle: "dashed"
    linewidth: 3
    r_start: 68
    r_end: 68
    months: ["Mar", "Apr", "May","Jun","Jul","Aug","Sep"]

  usace_communication:
    type: "line"
    color: "hydrological_forecasting.communication"
    linestyle: "dashdot"
    linewidth: 3
    r_start: 66
    r_end: 66
    months: ["Apr", "May"]


  #################################################################################
  # River Ice Monitoring
  #################################################################################
  river_ice_monitoring_critical_a:
    type: "infill"
    color: "river_ice_monitoring.critical_period"
    linestyle: "-"
    alpha: 0.5
    linewidth: 3
    r_start: 54
    r_end: 64
    months: ["Apr", "May", "Oct", "Nov"]

  river_ice_monitoring_critical_b:
    type: "infill"
    color: "river_ice_monitoring.critical_period"
    linestyle: "-"
    alpha: 0.2
    linewidth: 3
    r_start: 54
    r_end: 64
    months: ["Mar", "Apr", "May", "Oct", "Nov"]

  river_ice_meteo_hydro:
    type: "line"
    color: "river_ice_monitoring.data"
    linestyle: "-"
    linewidth: 3
    r_start: 63
    r_end: 63
    months: ["Mar","Apr", "May", "Oct", "Nov"]

  remote_sensing_river_ice:
    type: "line"
    color: "river_ice_monitoring.data"
    linestyle: "dashed"
    linewidth: 3
    r_start: 61
    r_end: 61
    months: ["Apr", "May", "Oct", "Nov"]

  airborne_observations:
    type: "line"
    color: "river_ice_monitoring.data"
    linestyle: "dotted"
    linewidth: 3
    r_start: 59
    r_end: 59
    months: ["Apr", "May"]

  river_ice_monitoring_communication:
    type: "line"
    color: "river_ice_monitoring.communication"
    linestyle: "dashed"
    linewidth: 3
    r_start: 57
    r_end: 57
    months: ["Mar","Apr", "May", "Oct", "Nov"]

  spring_breakup_outlook_ice:
    type: "marker"
    color: "visualization.spring_breakup_outlook"
    marker: "P"
    markersize: 10
    linewidth: 3
    months: ["Apr"]
    r_points:
      Apr: 55
    position: 0.75


  #################################################################################
  # Planning and Improvement
  #################################################################################
  planning_and_improvement_critical:
    type: "infill"
    color: "planning_and_improvement.critical_period"
    alpha: 0.5
    linewidth: 3
    r_start: 45
    r_end: 53
    months: ["Sep","Oct", "Nov", "Dec", "Jan", "Feb", "Mar", "Apr"]

  planning_and_improvement_reporting:
    type: "line"
    color: "planning_and_improvement.admin"
    linestyle: "dashed"
    linewidth: 3
    r_start: 52
    r_end: 52
    months: ["Sep","Oct", "Nov", "Dec", "Jan", "Feb", "Mar"]

  planning_and_improvement_documentation:
    type: "line"
    color: "planning_and_improvement.admin"
    linestyle: "dotted"
    linewidth: 3
    r_start: 50
    r_end: 50
    months: ["Sep","Oct", "Nov", "Dec", "Jan", "Feb", "Mar"]

  planning_and_improvement_process_improvement:
    type: "line"
    color: "planning_and_improvement.capacity"
    linestyle: "dashdot"
    linewidth: 5
    r_start: 48
    r_end: 48
    months: ["Sep","Oct", "Nov", "Dec", "Jan", "Feb", "Mar"]

  planning_and_improvement_no_modifications:
    type: "line"
    color: "planning_and_improvement.block"
    linestyle: "dashdot"
    linewidth: 5
    r_start: 46
    r_end: 46
    months: ["Apr"]

  #################################################################################
  # Data Plot Tracks for Streamflow and SWE
  #################################################################################
  streamflow_data:
    type: "data_plot"
    data_type: "streamflow"
    color_mean: "visualization.streamflow"
    color_envelope: "visualization.streamflow"
    r_start: 24
    r_end: 36
    months: ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]

  swe_data:
    type: "data_plot"
    data_type: "swe"
    color_mean: "visualization.swe"
    color_envelope: "visualization.swe"
    r_start: 36
    r_end: 45
    months: ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]

################################################################################
# Plot Settings
################################################################################
plot_settings:
  figsize:
    plot: [30, 16]
  titles:
    plot: "Decision Calendars for the Chena River"
  legend:
    loc: "lower center"
    bbox: [0.0, -0.1]
    fontsize: 14
    title_fontsize: 14
    borderpad: 2
    labelspacing: 1.2
    facecolor: "white"
    edgecolor: "black"

################################################################################
# Legend Groups
################################################################################
legend_groups:
  Annual_Activities:
    description: "Annual Activities"
    color: "annual_activities.critical_period"
    elements:
      - type: space
      - type: line
        color: "annual_activities.data"
        linestyle: "dashed"
        linewidth: 3
        label: "CHPS Operations"
      - type: line
        color: "annual_activities.data"
        linestyle: "dotted"
        linewidth: 3
        label: "Alaska Stream Gauge Observing Program"
      - type: space

  Snow_Seasonal_Forecasting:
    color: "snow_forecasting.critical_period"
    elements:
      - type: space
      - type: line
        color: "snow_forecasting.data"
        linestyle: "-"
        linewidth: 3
        label: "Meteo and Hydro Stations"
      - type: line
        color: "snow_forecasting.data"
        linestyle: "dotted"
        linewidth: 3
        label: "Large Domain Snow Products"
      - type: line
        color: "snow_forecasting.data"
        linestyle: "dashdot"
        linewidth: 3
        label: "Temperature Outlook - CPEC"
      - type: marker
        color: "visualization.snow_survey"
        marker: "v"
        markersize: 10
        linewidth: 3
        label: "Snow Surveys"
      - type: space
      - type: line
        color: "snow_forecasting.forecast"
        linestyle: "-"
        linewidth: 3
        label: "Snow Based Seasonal Forecasts"
      - type: space
      - type: marker
        color: "visualization.spring_breakup_outlook"
        marker: "P"
        markersize: 10
        linewidth: 3
        label: "Spring Breakup Outlook"
      - type: space

  Hydro_Shortterm_Outlook:
    description: "Hydro Short-term Outlook"
    color: "hydrological_forecasting.critical_period"
    elements:
      - type: space
      - type: line
        color: "hydrological_forecasting.data"
        linestyle: "-"
        linewidth: 3
        label: "Meteo and Hydro Station"
      - type: line
        color: "hydrological_forecasting.data"
        linestyle: "dashed"
        linewidth: 3
        label: "NWP Forecasts"
      - type: line
        color: "hydrological_forecasting.data"
        linestyle: "dotted"
        linewidth: 3
        label: "Meteorologist (APRFC, AFG, CPC)"
      - type: space
      - type: line
        color: "hydrological_forecasting.forecast"
        linestyle: "dashed"
        linewidth: 3
        label: "CHPS Forecasts"
      - type: line
        color: "hydrological_forecasting.forecast"
        linestyle: "dotted"
        linewidth: 3
        label: "HEFS Forecasts"
      - type: line
        color: "hydrological_forecasting.forecast"
        linestyle: "dashdot"
        linewidth: 3
        label: "1-2 Week Outlook (GEFS, ECWMF, NBM)"
      - type: space
      - type: line
        color: "hydrological_forecasting.communication"
        linestyle: "dotted"
        linewidth: 3
        label: "NWS APRFC Portal"
      - type: line
        color: "hydrological_forecasting.communication"
        linestyle: "dashed"
        linewidth: 3
        label: "Event Based - Broad Stakeholder Comms"
      - type: line
        color: "hydrological_forecasting.communication"
        linestyle: "dashdot"
        linewidth: 3
        label: "USACE Coordination and Comms"
      - type: space

  River_Ice_Monitoring:
    description: "River Ice Monitoring"
    color: "river_ice_monitoring.critical_period"
    elements:
      - type: space
      - type: line
        color: "river_ice_monitoring.data"
        linestyle: "-"
        linewidth: 3
        label: "Meteo and Hydro Data"
      - type: line
        color: "river_ice_monitoring.data"
        linestyle: "dashed"
        linewidth: 3
        label: "Remote Sensing"
      - type: line
        color: "river_ice_monitoring.data"
        linestyle: "dotted"
        linewidth: 3
        label: "Airborne Observations"
      - type: space
      - type: marker
        color: "visualization.spring_breakup_outlook"
        marker: "P"
        markersize: 10
        linewidth: 3
        label: "Spring Breakup Outlook"
      - type: line
        color: "river_ice_monitoring.communication"
        linestyle: "dashed"
        linewidth: 3
        label: "River Watch"
      - type: space

  Planning_and_Improvement:
    description: "Planning and Improvement"
    color: "planning_and_improvement.critical_period"
    elements:
      - type: space
      - type: line
        color: "planning_and_improvement.admin"
        linestyle: "dashed"
        linewidth: 3
        label: "National Program Activities"
      - type: line
        color: "planning_and_improvement.admin"
        linestyle: "dotted"
        linewidth: 3
        label: "Internal Process Improvement"
      - type: space
      - type: line
        color: "planning_and_improvement.capacity"
        linestyle: "dashdot"
        linewidth: 5
        label: "Capacity for Process Improvement"
      - type: space
      - type: line
        color: "planning_and_improvement.block"
        linestyle: "dashdot"
        linewidth: 5
        label: "No Upgrades Ahead of Operations"
      - type: space
    
  SWE_Annual_Range:
    description: "Seasonal Data"
    color: "visualization.swe"
    elements:
      - type: space

  Streamflow_Annual_Range:
    description: "Streamflow Data"
    color: "visualization.streamflow"
    elements:
      - type: space

