# ross.yaml

data_paths:
  streamflow: "/Users/dcasson/Data/yukon_esp/observations/Chena_Near_Two_Rivers_streamflow_climatology.csv"
  swe: "/Users/dcasson/Data/yukon_esp/observations/Chena_Near_Two_Rivers_SWE_processed_948_HRU132.csv"






colors:
  # Snow Forecasting Color Scheme
  snow_forecasting:
    critical_period: "#66c2a5"       # Blue
    data: "#e41a1c"                  # Purple
    forecast: "#377eb8"              # Orange
    communication: "#4daf4a"          # Green

  # Hydrological Forecasting Color Scheme
  hydrological_forecasting:
    critical_period: "#8da0cb"        # Yellow
    data: "#e41a1c"                  # Purple
    forecast: "#377eb8"              # Orange
    communication: "#4daf4a"          # Green

  # River Ice Monitoring Color Scheme
  river_ice_monitoring:
    critical_period: "#b3b3b3"       # Gray
    data: "#e41a1c"                  # Purple
    forecast: "#377eb8"              # Orange
    communication: "#4daf4a"          # Green

  # Planning and Improvement Color Scheme
  planning_and_improvement:
    critical_period: "#e5c494"        # Yellow
    admin: "#bebada"                  # Purple
    capacity: "#8dd3c7"                # Green
    block: "#000000"                  # Black

  # Visualization and Other Elements
  visualization:
    snow_survey: "#e41a1c"             # Red
    snow_bulletin: "#4daf4a"           # Green
    streamflow: "#984ea3"             # Red
    swe: "#0000FF"                   # Blue

styles:
  # Line Styles
  solid:
    linestyle: "-"
    linewidth: 3

  dashed:
    linestyle: "--"
    linewidth: 3

  dotted:
    linestyle: ":"
    linewidth: 3

  dashdot:
    linestyle: "-."
    linewidth: 3

  # Marker Styles
  downward_triangle:
    marker: "v"
    markersize: 10
    markeredgewidth: 2
    markerfacecolor: "visualization.snow_survey"  # Reference to color

  diamond:
    marker: "P"
    markersize: 10
    markeredgewidth: 2
    markerfacecolor: "visualization.snow_bulletin"  # Reference to color

month_ranges:
  Jan: [1, 31]
  Feb: [32, 59]
  Mar: [60, 90]
  Apr: [91, 120]
  May: [121, 151]
  Jun: [152, 181]
  Jul: [182, 212]
  Aug: [213, 243]
  Sep: [244, 273]
  Oct: [274, 304]
  Nov: [305, 334]
  Dec: [335, 365]

sectors:
  Jan: 1
  Feb: 1
  Mar: 1
  Apr: 1
  May: 1
  Jun: 1
  Jul: 1
  Aug: 1
  Sep: 1
  Oct: 1
  Nov: 1
  Dec: 1

track_configs:

  # Snow Seasonal Forecasting
  snow_based_seasonal_forecasts_critical:
    type: "infill"
    color: "snow_forecasting.critical_period"
    alpha: 0.5
    r_start: 84
    r_end: 100
    months: ["Mar", "Apr", "May"]
  
  snow_based_seasonal_forecasts_total:
    type: "infill"
    color: "snow_forecasting.critical_period"
    alpha: 0.2
    r_start: 84
    r_end: 100
    months: ["Nov", "Dec", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul","Aug"]

  snow_based_flood_risk_forecasts:
    type: "line"
    color: "snow_forecasting.forecast"
    linestyle: "--"
    linewidth: 5
    r_start: 93
    r_end: 95
    months: ["Mar", "Apr"]

  snow_based_forecast_1:
    type: "line"
    color: "snow_forecasting.forecast"
    linestyle: "-"
    linewidth: 3
    r_start: 91
    r_end: 93
    months: ["Mar", "Apr", "May", "Jun", "Jul","Aug"]

  snow_based_forecast_2:
    type: "line"
    color: "snow_forecasting.forecast"
    linestyle: "-"
    linewidth: 3
    r_start: 89
    r_end: 91
    months: ["Apr", "May", "Jun", "Jul","Aug"]

  snow_based_forecast_3:
    type: "line"
    color: "snow_forecasting.forecast"
    linestyle: "-"
    linewidth: 3
    r_start: 87
    r_end: 89
    months: ["May", "Jun", "Jul","Aug"]

  automated_station_data:
    type: "line"
    color: "snow_forecasting.data"
    linestyle: "-"
    linewidth: 3
    r_start: 97
    r_end: 99
    months: ["Nov","Dec", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul","Aug"]

  large_domain_snow_products:
    type: "line"
    color: "snow_forecasting.data"
    linestyle: ":"
    linewidth: 3
    r_start: 95
    r_end: 97
    months: ["Nov", "Dec", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul","Aug"]
  
  snow_flood_risk_communication:
    type: "line"
    color: "snow_forecasting.communication"
    linestyle: "dotted"
    linewidth: 3
    r_start: 85
    r_end: 87
    months: ["Dec","Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul","Aug"]

  snow_surveys:
    type: "marker"
    color: "visualization.snow_survey"
    marker: "v"
    markersize: 10
    linewidth: 3
    months: ["Feb", "Mar", "Apr"]
    r_points:
      Feb: 91
      Mar: 89
      Apr: 87
    position: 0.75

  snow_bulletin:
    type: "marker"
    color: "visualization.snow_bulletin"
    marker: "P"
    markersize: 10
    linewidth: 3
    months: ["Mar", "Apr", "May"]
    r_points:
      Mar: 85
      Apr: 85
      May: 85
    position: 0.25

  #################################################################################
  # Hydrological Short Term
  #################################################################################
  hydrological_critical_period:
    type: "infill"
    color: "hydrological_forecasting.critical_period"
    alpha: 0.5
    r_start: 65
    r_end: 80
    months: ["May", "Jun", "Jul"]
  
  hydrological_total:
    type: "infill"
    color: "hydrological_forecasting.critical_period"
    alpha: 0.2
    r_start: 65
    r_end: 80
    months: ["Oct", "Nov", "Dec", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep"]

  hydrometric_observations:
    type: "line"
    color: "hydrological_forecasting.data"
    linestyle: "-"
    linewidth: 3
    r_start: 77
    r_end: 79
    months: ["Oct", "Nov", "Dec", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep"]
  
  nwp_forecasts:
    type: "line"
    color: "hydrological_forecasting.data"
    linestyle: "dashed"
    linewidth: 3
    r_start: 75
    r_end: 77
    months: ["Oct", "Nov", "Dec", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep"]

  hydrologic_short_term_forecasts:
    type: "line"
    color: "hydrological_forecasting.forecast"
    linestyle: "-"
    linewidth: 3
    r_start: 73
    r_end: 75
    months: [ "May", "Jun", "Jul", "Aug", "Sep", "Oct"]

  hydrologic_flood_altas_portal:
    type: "line"
    color: "hydrological_forecasting.communication"
    linestyle: "dashdot"
    linewidth: 3 
    r_start: 69
    r_end: 71
    months: ["Oct", "Nov", "Dec", "Jan","Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep"]

  hydrologic_communication_calls:
    type: "line"
    color: "hydrological_forecasting.communication"
    linestyle: "dotted"
    linewidth: 3
    r_start: 67
    r_end: 69
    months: ["Apr", "May", "Jun", "Jul", "Aug"]

  hydrologic_weekly_communication_calls:
    type: "line"
    color: "hydrological_forecasting.communication"
    linestyle: "dashed"
    linewidth: 3
    r_start: 71
    r_end: 73
    months: ["Oct", "Nov", "Dec", "Jan","Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep"]
  #################################################################################
  # River Ice Monitoring
  #################################################################################
  river_ice_monitoring:
    type: "infill"
    color: "river_ice_monitoring.critical_period"
    linestyle: "-"
    alpha: 0.5
    linewidth: 3
    r_start: 45
    r_end: 60
    months: ["Oct", "Nov", "Dec", "Apr", "May"]

  river_ice_meteo_hydro:
    type: "line"
    color: "river_ice_monitoring.data"
    linestyle: "-"
    linewidth: 3
    r_start: 57
    r_end: 59
    months: ["Oct", "Nov", "Dec", "Apr", "May"]
  remote_sensing_river_ice:
    type: "line"
    color: "river_ice_monitoring.data"
    linestyle: "dashed"
    linewidth: 3
    r_start: 55
    r_end: 57
    months: ["Oct", "Nov", "Dec", "Apr", "May"]

  airborne_observations:
    type: "line"
    color: "river_ice_monitoring.data"
    linestyle: "dotted"
    linewidth: 3
    r_start: 53
    r_end: 55
    months: ["Apr", "May"]

  citizen_observations:
    type: "line"
    color: "river_ice_monitoring.data"
    linestyle: "dashdot"
    linewidth: 3
    r_start: 51
    r_end: 53
    months: ["Apr", "May"]

  river_ice_flood_altas:
    type: "line"
    color: "river_ice_monitoring.communication"
    linestyle: "dashdot"
    linewidth: 3
    r_start: 49
    r_end: 51
    months: ["Apr", "May", "Oct", "Nov", "Dec"]
  
  river_ice_monitoring_communication:
    type: "line"
    color: "river_ice_monitoring.communication"
    linestyle: "dotted"
    linewidth: 3
    r_start: 47
    r_end: 49
    months: ["Apr", "May", "Oct", "Nov", "Dec"]


  #################################################################################
  # Planning and Improvement
  #################################################################################
  planning_and_improvement_critical:
    type: "infill"
    color: "planning_and_improvement.critical_period"
    alpha: 0.5
    linewidth: 3
    r_start: 30
    r_end: 40
    months: ["Sep","Oct", "Nov", "Dec", "Jan", "Feb", "Mar"]
  planning_and_improvement_reporting:
    type: "line"
    color: "planning_and_improvement.admin"
    linestyle: "dashed"
    linewidth: 3
    r_start: 37
    r_end: 39
    months: ["Sep","Oct", "Nov", "Dec", "Jan", "Feb"]
  planning_and_improvement_documentation:
    type: "line"
    color: "planning_and_improvement.admin"
    linestyle: "dotted"
    linewidth: 3
    r_start: 35
    r_end: 37
    months: ["Sep","Oct", "Nov", "Dec", "Jan", "Feb"]
  planning_and_improvement_process_improvement:
    type: "line"
    color: "planning_and_improvement.capacity"
    linestyle: "dashdot"
    linewidth: 5
    r_start: 33
    r_end: 35
    months: ["Sep","Oct", "Nov", "Dec", "Jan", "Feb"]
  planning_and_improvement_no_modifications:
    type: "line"
    color: "planning_and_improvement.block"
    linestyle:  "dashdot"
    linewidth: 5
    r_start: 33
    r_end: 35
    months: ["Mar"]

plot_settings:
  figsize:
    plot: [18, 15]
    observations: [12, 6]
  titles:
    plot: "Decision Calendars for the Ross River"
    observations: "Observations"
  legend:
    loc: "lower center"            # Positioning is handled manually in the function
    bbox: [0.0, -0.1]             # Starting x and y coordinates for the legends
    fontsize: 16                   # Font size for legend entries
    title_fontsize: 18             # Font size for legend headers
    borderpad: 2
    labelspacing: 1.2
    facecolor: "white"             # Background color of the legends
    edgecolor: "black"             # Border color of the legends

legend_groups:
  Snow_Seasonal_Forecasting:
    description: "Snow Seasonal Forecasting"
    elements:
      - type: space
      - type: patch
        color: "snow_forecasting.critical_period"
        label: "Critical Period - Snow Seasonal"
      - type: space
      - type: line
        color: "snow_forecasting.data"
        linestyle: "-"
        linewidth: 3
        label: "Meteo and Hydro Stations"
      - type: line
        color: "snow_forecasting.data"
        linestyle: ":"
        linewidth: 3
        label: "Large Domain Snow Products"
      - type: marker
        color: "visualization.snow_survey"
        marker: "v"
        markersize: 10
        linewidth: 3
        label: "Snow Surveys"
      - type: space
      - type: line
        color: "snow_forecasting.forecast"
        linestyle: "dashed"
        linewidth: 5
        label: "Flood Risk Assessment"
      - type: line
        color: "snow_forecasting.forecast"
        linestyle: "-"
        linewidth: 3
        label: "Snow Based Forecasts"

      - type: space
      - type: line
        color: "snow_forecasting.communication"
        linestyle: "dotted"
        linewidth: 3
        label: "Snow Flood Risk Communication"
      - type: marker
        color: "visualization.snow_bulletin"
        marker: "P"
        markersize: 10
        linewidth: 3
        label: "Snow Bulletin"


  Hydro_Shortterm_Outlook:
    description: "Hydro Short-term Outlook"
    elements:
      - type: space
      - type: patch
        color: "hydrological_forecasting.critical_period"
        label: "Critical Period - Hydro Short Term"
      - type: space
      - type: line
        color: "hydrological_forecasting.data"
        linestyle: "-"
        linewidth: 3
        label: "Meteo and Hydro Stations"
      - type: line
        color: "hydrological_forecasting.data"
        linestyle: "dashed"
        linewidth: 3
        label: "NWP Forecasts"
      - type: space
      - type: space
      - type: line
        color: "hydrological_forecasting.forecast"
        linestyle: "-"
        linewidth: 3
        label: "Model Based Forecasts"
      - type: space
      - type: line
        color: "hydrological_forecasting.communication"
        linestyle: "dashdot"
        linewidth: 3
        label: "Flood Altas Portal"
      - type: line
        color: "hydrological_forecasting.communication"
        linestyle: "dotted"
        linewidth: 3
        label: "Event Based Communication"
      - type: line
        color: "hydrological_forecasting.communication"
        linestyle: "dashed"
        linewidth: 3
        label: "Emergency Management Calls"


  River_Ice_Monitoring:
    description: "River Ice Monitoring"
    elements:
      - type: space
      - type: patch
        color: "river_ice_monitoring.critical_period"
        label: "Critical Period - River Ice"
      - type: space
      - type: line
        color: "river_ice_monitoring.data"
        linestyle: "-"
        linewidth: 3
        label: "Meteo and Hydro Stations"
      - type: line
        color: "river_ice_monitoring.data"
        linestyle: "dashed"
        linewidth: 3
        label: "Remote Sensing"
      - type: line
        color: "river_ice_monitoring.data"
        linestyle: "dotted"
        linewidth: 3
        label: "Airborne Observations"
      - type: line
        color: "river_ice_monitoring.data"
        linestyle: "dashdot"
        linewidth: 3
        label: "Citizen Observations"
      - type: space
      - type: space
      - type: line
        color: "river_ice_monitoring.communication"
        linestyle: "dashdot"
        linewidth: 3
        label: "Flood Altas Portal"
      - type: line
        color: "river_ice_monitoring.communication"
        linestyle: "dotted"
        linewidth: 3
        label: "Event Based Communication"

  Planning_and_Improvement:
    description: "Planning and Improvement"
    elements:
      - type: space
      - type: patch
        color: "planning_and_improvement.critical_period"
        label: "Critical Period - Planning and Improvement"
      - type: line
        color: "planning_and_improvement.admin"
        linestyle: "dashed"
        linewidth: 3
        label: "Reporting on Hydrometric Data"
      - type: line
        color: "planning_and_improvement.admin"
        linestyle: "dotted"
        linewidth: 3
        label: "Document Breakup + Community Information"
      - type: line
        color: "planning_and_improvement.capacity"
        linestyle: "dashdot"
        linewidth: 5
        label: "Capacity for Process Improvement"
      - type: line
        color: "planning_and_improvement.block"
        linestyle: "dashdot"
        linewidth: 5
        label: "No Upgrades Ahead of Operations"
